### ISSUE TITLE
缺少基础依赖jar包

### ISSUE THREAD

**Issue by classcit** [harmonycloud/zeus#39]
<caas.version>3.0.1-middleware</caas.version>
<harmonycloud.tools.version>1.0.1-middleware</harmonycloud.tools.version>
这两个包没有

**Comment by KarlCyan** [comment]
已知问题,解决内部依赖项目问题

**Comment by fanzhenyu95** [comment]
同样的问题，请问如何解决？

**Comment by Jaywoods2** [comment]
同样的问题，请问如何解决？

**Comment by Jaywoods2** [comment]
@classcit @KarlCyan
